"use strict";
exports.__esModule = true;
var visibilityReducer_1 = require("./visibilityReducer");
var expect_1 = require("expect");
var deep_freeze_1 = require("deep-freeze");
var state_before1 = { todos1: [], visibility: 'SHOW_ALL' };
var state_before2 = { todos2: [], visibility: 'SHOW_COMPLETED' };
var state_after1 = { todos1: [], visibility: 'SHOW_COMPLETED' };
var state_after2 = { todos2: [], visibility: 'SHOW_LEFT' };
deep_freeze_1["default"](state_before1);
deep_freeze_1["default"](state_before2);
expect_1["default"](visibilityReducer_1["default"](state_before1, { type: 'SHOW_COMPLETED' })).toEqual(state_after1);
expect_1["default"](visibilityReducer_1["default"](state_before2, { type: 'SHOW_LEFT' })).toEqual(state_after2);
console.log('all tests passed!');
